sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
   host: localhost
   port: 6379
   password:
   database: 1

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHsMcCKzUBsJHdk5NKG
    access-key-secret: 7nguxBT2r7ilgUiaA4JasRon5XLqTP
    bucket-name: web-kano